"""initial schema

Revision ID: 231dce52a4eb
Revises:
Create Date: 2026-09-10 10:06:55.425176

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "231dce52a4eb"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "matches",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("game_id", sa.String(length=64), nullable=False),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.Column("mode", sa.String(length=32), nullable=False),
        sa.Column("player_count", sa.Integer(), nullable=False),
        sa.Column("turn_seconds", sa.Integer(), nullable=False),
        sa.Column("turns", sa.Integer(), nullable=False),
        sa.Column("ranked", sa.Boolean(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("reason", sa.String(length=32), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("matches", schema=None) as batch_op:
        batch_op.create_index("ix_matches_recent", ["status", "started_at"], unique=False)

    op.create_table(
        "otp_codes",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("email", sa.String(length=254), nullable=False),
        sa.Column("code_hash", sa.String(length=64), nullable=False),
        sa.Column("purpose", sa.String(length=32), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("consumed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("otp_codes", schema=None) as batch_op:
        batch_op.create_index("ix_otp_lookup", ["email", "purpose"], unique=False)

    op.create_table(
        "players",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("username", sa.String(length=32), nullable=True),
        sa.Column("email", sa.String(length=254), nullable=True),
        sa.Column("email_verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("google_id", sa.String(length=64), nullable=True),
        sa.Column("password_hash", sa.Text(), nullable=True),
        sa.Column("rating", sa.Integer(), nullable=False),
        sa.Column("games_played", sa.Integer(), nullable=False),
        sa.Column("wins", sa.Integer(), nullable=False),
        sa.Column("losses", sa.Integer(), nullable=False),
        sa.Column("draws", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("google_id"),
        sa.UniqueConstraint("username"),
    )
    with op.batch_alter_table("players", schema=None) as batch_op:
        batch_op.create_index("ix_players_ranking", ["kind", "rating"], unique=False)

    op.create_table(
        "friendships",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("requester_id", sa.String(length=64), nullable=False),
        sa.Column("addressee_id", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("responded_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["addressee_id"], ["players.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["requester_id"], ["players.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("requester_id", "addressee_id", name="uq_friend_pair"),
    )
    with op.batch_alter_table("friendships", schema=None) as batch_op:
        batch_op.create_index("ix_friendships_addressee", ["addressee_id", "status"], unique=False)

    op.create_table(
        "match_actions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("match_id", sa.String(length=64), nullable=False),
        sa.Column("turn", sa.Integer(), nullable=False),
        sa.Column("seat", sa.Integer(), nullable=False),
        sa.Column("detail", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["match_id"], ["matches.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("match_id", "turn", name="uq_match_turn"),
    )
    op.create_table(
        "match_players",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("match_id", sa.String(length=64), nullable=False),
        sa.Column("player_id", sa.String(length=64), nullable=True),
        sa.Column("seat", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("is_bot", sa.Boolean(), nullable=False),
        sa.Column("bot_level", sa.String(length=16), nullable=True),
        sa.Column("score", sa.Integer(), nullable=False),
        sa.Column("retired", sa.Boolean(), nullable=False),
        sa.Column("winner", sa.Boolean(), nullable=False),
        sa.Column("rating_before", sa.Integer(), nullable=True),
        sa.Column("rating_after", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["match_id"], ["matches.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["player_id"], ["players.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("match_id", "seat", name="uq_match_seat"),
    )
    with op.batch_alter_table("match_players", schema=None) as batch_op:
        batch_op.create_index("ix_match_players_player", ["player_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("match_players", schema=None) as batch_op:
        batch_op.drop_index("ix_match_players_player")

    op.drop_table("match_players")
    op.drop_table("match_actions")
    with op.batch_alter_table("friendships", schema=None) as batch_op:
        batch_op.drop_index("ix_friendships_addressee")

    op.drop_table("friendships")
    with op.batch_alter_table("players", schema=None) as batch_op:
        batch_op.drop_index("ix_players_ranking")

    op.drop_table("players")
    with op.batch_alter_table("otp_codes", schema=None) as batch_op:
        batch_op.drop_index("ix_otp_lookup")

    op.drop_table("otp_codes")
    with op.batch_alter_table("matches", schema=None) as batch_op:
        batch_op.drop_index("ix_matches_recent")

    op.drop_table("matches")
    # ### end Alembic commands ###
